import { AppConfig, Candidate } from '../types';

export const seedConfig: AppConfig = {
    projectName: 'Voto Consciente',
    logo: '',
    headerImage: '',
    mapTitle: 'Mapa do Brasil',
    primaryColor: '#1D4ED8',
    secondaryColor: '#3B82F6',
    mapColorEmpty: '#D1D5DB',
    mapColorFilled: '#BFDBFE',
    mapColorHover: '#1D4ED8',
    aboutText: 'Conheça os candidatos e vote com consciência.',
    footerText: '© 2026 Voto Consciente.',
    footerContact: '',
    theme: 'light',
};

export const seedCandidates: Candidate[] = [
    {
        id: '1',
        name: 'João Silva',
        fullName: 'João Silva dos Santos',
        photo: '',
        partyName: 'Partido Exemplo A',
        partyAbbr: 'PEA',
        campaignNumber: '10',
        cargo: 'deputado-federal',
        state: 'SP',
        description: 'Candidato comprometido com a educação e saúde pública.',
        socialLinks: {
            instagram: 'https://instagram.com',
            facebook: 'https://facebook.com',
        },
        websiteUrl: 'https://exemplo.com',
        createdAt: new Date().toISOString(),
        active: true,
    },
    {
        id: '2',
        name: 'Maria Santos',
        fullName: 'Maria Santos da Silva',
        photo: '',
        partyName: 'Partido Exemplo B',
        partyAbbr: 'PEB',
        campaignNumber: '20',
        cargo: 'senador',
        state: 'RJ',
        description: 'Lutando por mais investimentos em infraestrutura e desenvolvimento social.',
        socialLinks: {
            twitter: 'https://twitter.com',
            youtube: 'https://youtube.com',
        },
        createdAt: new Date().toISOString(),
        active: true,
    },
    {
        id: '3',
        name: 'Carlos Oliveira',
        fullName: 'Carlos Oliveira Pereira',
        photo: '',
        partyName: 'Partido Exemplo C',
        partyAbbr: 'PEC',
        campaignNumber: '30',
        cargo: 'governador',
        state: 'MG',
        description: 'Experiência em gestão pública e compromisso com o desenvolvimento de Minas Gerais.',
        socialLinks: {
            instagram: 'https://instagram.com',
            linkedin: 'https://linkedin.com',
        },
        websiteUrl: 'https://exemplo.com',
        createdAt: new Date().toISOString(),
        active: true,
    },
    {
        id: '4',
        name: 'Ana Paula Costa',
        fullName: 'Ana Paula Costa Lima',
        photo: '',
        partyName: 'Partido Exemplo D',
        partyAbbr: 'PED',
        campaignNumber: '40',
        cargo: 'prefeito',
        state: 'SP',
        municipality: 'São Paulo',
        description: 'Defensora dos direitos humanos e da justiça social.',
        socialLinks: {
            instagram: 'https://instagram.com',
            facebook: 'https://facebook.com',
            twitter: 'https://twitter.com',
        },
        createdAt: new Date().toISOString(),
        active: true,
    },
];
